### ISSUE TITLE
stale compiled output served by builder on subsequent rebuilds

### ISSUE THREAD

**Issue by kwesterfeld** [alexisvincent/systemjs-tools#14]
I am performing the following workflow:
 - start with no cache in systemjs-tools
 - hit refresh on browser, see the state of the markup (1)
 - wait 45s for build to complete
 - change application .html file (2)
 - witness HMR hotswap in the browser--yeah!
 - hit refresh on browser
 - wait 5s for build to complete, which is NICE and FAST, but uses old .js and/or .html 
 - see browser has reverted to remove the change in (2) above, and you will see (1) instead

In looking at this, it seems the _.cache.builder is stale.  I tried to evict the .html from _.builder.cache.compile.loads and _.builder.cache.trace, but no dice.  It seems keeping the _.cache.builder reuse is broken, which is unfortunate because my app could really use the 5s reload!

**Comment by kwesterfeld** [comment]
Actually, I take it back...if I knock out BOTH _.builder.cache.compile.loads and _.builder.cache.trace the browser refresh works again.

PR will be coming on this

**Comment by kwesterfeld** [comment]
@alexisvincent if you review this scenario, you will see the issue I am dealing with is static content and serving stale stuff post-invalidate.  I will put some more time into this and narrow down where in the build pipeline the problem is introduced.

**Comment by alexisvincent** [comment]
I suspect this is an issue with the builder project itself. If builder.invalidate does not remove those entries from the cache then that’s where the problem is :)

**Comment by kwesterfeld** [comment]
Perhaps the issue is even simpler.

My app does not use the root webapp context, instead serves from a context as "smc".   So if asset "smc/app/nav.html" changes, the invalidation being passed is "smc/app/nav.html", but the cache is actually holding onto "app/nav.html", since the cache is constructed with "app/main.js" as its entrypoint.   

It seems the baseURL is not being utilized when doing cache invalidation.  I think this will end up being a much easier change for you to review in a few.

**Comment by alexisvincent** [comment]
Aha! Makes sense, although I really thought I was dealing with this. Are you sure your baseurl is included in a config that gets loaded in tools, and that your load order doesn’t overwrite anything

**Comment by kwesterfeld** [comment]
I am certain the baseURL is not being passed properly to the cache.  I walked the code, and it is being passed "smc/app/nav.html" in this case, and its internal cache is looking at "app/nav.html".  In this case "smc" is the value assigned to baseURL.
