### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by beldur** [alexisvincent/systemjs-tools#2]
Hi,

I'm trying to install systemjs-tools with yarn but get the following error. I'm not sure if this is a problem on yarn's side or systemjs-tools side:

```
$ yarn global add systemjs-tools
yarn global v0.19.1
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/systemjs-hmr/-/systemjs-hmr-0.1.8.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/home/xxx/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by alexisvincent** [comment]
@beldur  systemjs-tools doesn't even have working docs atm :) But I'm happy to help you get it up and running via this issue before I finish the docs. Will try fix up the install atm. Thanks for reporting.

**Comment by alexisvincent** [comment]
@beldur New release is up. Tell me if it works for you?

**Comment by beldur** [comment]
yep. thx!

**Comment by alexisvincent** [comment]
Awesome. Are you installing `systemjs-tools` for the config builder, or for a better dev workflow?

**Comment by beldur** [comment]
I wanted to try out the config builder

**Comment by alexisvincent** [comment]
Oh ok :) ATM it isn't ready, there's still cases it doesn't work for and so needs work before it becomes a viable alternative to JSPM.
